server.port=8080
spring.application.name=application-system

spring.datasource.url=jdbc:h2:mem:applications
spring.datasource.driver-class-name=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=


spring.jpa.hibernate.ddl-auto=create-drop
spring.jpa.show-sql=true
spring.jpa.defer-datasource-initialization=true


spring.h2.console.enabled=true
spring.h2.console.path=/h2-console

# --- Actuator ---
management.endpoints.web.exposure.include=health,info,metrics,beans,mappings
management.endpoint.health.show-details=always
management.info.env.enabled=true
info.app.name=Application System
info.app.description=System obslugi wnioskow — sektor publiczny
info.app.version=1.0.0